# Generated by Django 4.2.17 on 2025-01-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('disease_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease_tracker.disease')),
            ],
        ),
    ]
